### PR TITLE
On ticker updates. map Ticker.currencyPair to the CurrencyPairDto provided in the strategy

### PR DESCRIPTION
**Pull request by xblaatx**
…entation

 => When recieving tickers from Xchange. map the Ticker.currencyPair to the CurrencyPairDto provided in the strategy. Doing it this way also the precision spefified is used.

 => created a method in the tickerMapper for this.

 => added a Test

### CODE REVIEW

**Comment by xblaatx** [comment]
@straumat I dont know why the tests are failing. Can u help me out?

**Comment by sebasira** [comment]
@xblaatx I have not seen this before! I have just submitted a PR for this same issue

**Comment by xblaatx** [comment]
> @xblaatx I have not seen this before! I have just submitted a PR for this same issue

Cool. Are your tests running without error?

**Comment by sebasira** [comment]
Yes! Here it is: https://github.com/cassandre-tech/cassandre-trading-bot/pull/862

**Pull request closed without merging**
