### PR TITLE
Added bar aggregation for ta4j strategy... very simplistic version :)

### PR DESCRIPTION
**Pull request by petrmac**
Currently, the signals in ta4j strategy are incorrect. The case is that the bars needed for ta4j analysis are not properly constructed and for some exchanges don't have all properties - mostly open price is either missing (kucoin) or is static (coinbase pro). 
This completely messes up the analysis in ta4j, especially when indicator is based on faulty element.

This tries to fix it by adding simple aggregation by duration and calculation of highs and lows based on ticker data.
The time is not sticky to full minute start/end, but we can add this later. For the time being, the duration is at least enforced and the bar should now have all elements (OHLC + V).

### CODE REVIEW

**Comment by MarcDahlem** [comment]
Hey @petrmac 
your PR introduces a lot of code to calculate the open price and to correct the last bar. This is kind of risky and could have e.g. some problems in edge-cases etc.

Did you check directly with ta4j, because as far as I know they have already options to solve thie problem?

Option 1: The last bar can be replaced in ta4j, e.g. with https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BarSeries.java#L171

Option 2:  New trades and prices can be added to the last bar in ta4j with 'addTrade' or 'addPrice' https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BarSeries.java#L301

Option 3: Read the open price out of ta4j instead of getting it from the ticker: series.getLastBar().getOpenPrice()
Especially bar.addPrice(x) updates the open, close, high, and low price: https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BaseBar.java#L392

Maybe this eases the PR...

**Comment by MarcDahlem** [comment]
What about the following? https://github.com/MarcDahlem/cassandre-trading-bot/commit/4ff2e1fa8a61887ab5e46b39b0ef3a9b04a3a967

This should work (altough it doesnt update the endtime of the bars).

**Comment by petrmac** [comment]
Hey, thanks, @MarcDahlem, I'll check that out tomorrow in detail.

**Comment by MarcDahlem** [comment]
And here a version which should also update the timestamps correctly (I didnt check if the initial Duration.Zero works):
https://github.com/MarcDahlem/cassandre-trading-bot/commit/623835bedd765dec736a9dcbc8ec620401b22d30

**Comment by petrmac** [comment]
> Hey @petrmac
> your PR introduces a lot of code to calculate the open price and to correct the last bar. This is kind of risky and could have e.g. some problems in edge-cases etc.
> 
> Did you check the options available in ta4j, because as far as I know they have already options to solve this live-update-problem?
> 
> Option 1: The last bar can be replaced in ta4j, e.g. with https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BarSeries.java#L171
> 
> Option 2: New trades and prices can be added to the last bar in ta4j with 'addTrade' or 'addPrice' https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BarSeries.java#L301
> 
> Option 3: Read the open price out of ta4j instead of getting it from the ticker: series.getLastBar().getOpenPrice()
> Especially bar.addPrice(x) updates the open, close, high, and low price: https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BaseBar.java#L392
> 
> Maybe this eases the PR...

Hi @MarcDahlem, 
I checked the ta4j api that you mention and it is not a good fit. I can update only with one price (we are typically receiving more than just one) and there is missing method to update volume only. There is also an aggregator in ta4j, but this replaces whole series - which will not work for us.
Replacing a bar is not an option and I am somewhat against using an unfinished bar in the strategy - if we update the last bar live, we can run into concurrency problems. Hence I would think it is better to emit the bar in flux only after it is finished and run ta4j analysis on finished bars only. 
I also think it is better to aggregate bars outside the strategy, as this allows for a more testable and maintainable code.
Please note that the strategy is still receiving the ticker feed in realtime (or with delay set by rate limiter) so we can run stop loss in the strategy based on real time (not bar) data.

Instead of using ta4j, I have hardened the code and added more tests. Please let me know of any edge cases I have not covered!

**Comment by straumat** [comment]
Hi @MarcDahlem & @petrmac thanks a lot for your great work!
I made a release in between and updated some minor libraries. can you update your request?

**Comment by straumat** [comment]
@petrmac Great. So we are now only waiting for @MarcDahlem validation?

**Comment by MarcDahlem** [comment]
:-) I already gave him a thumb for looking into my suggestions and decided against.

For me this solution is also fine. The bar is updated only if it is fully available. And we dont have broken last bars anymore. Great!

**Pull request merged**
